//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpOrgWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmpAddressDet
    {
        public int AddressID { get; set; }

        [Display(Name = ("Address1"))]
        [Required]
        [MaxLength(50)]
        public string Address1 { get; set; }

        [Display(Name = ("Address2"))]
        [Required]
        [MaxLength(50)]
        public string Address2 { get; set; }

        [Display(Name = ("Employee Name"))]
        [Required]
        public int EmployeeID { get; set; }

        [Display(Name = ("State"))]
        [Required]
        public int StateID { get; set; }

        [Display(Name = ("Pincode"))]
        [Required]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Pincode must be Numeric.")]
        public int PinCode { get; set; }
    
        public virtual EmployeeMst EmployeeMst { get; set; }
        public virtual StateMst StateMst { get; set; }
    }
}
