//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpOrgWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeMst()
        {
            this.EmpAddressDets = new HashSet<EmpAddressDet>();
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int EmployeeID { get; set; }

        [Display(Name = ("First Name"))]
        [Required]
        [MaxLength(50)]
        public string FirstName { get; set; }

        [Display(Name = ("Middle Name"))]
        [MaxLength(50)]
        public string MiddleName { get; set; }

        [Display(Name = ("Last Name"))]
        [Required]
        [MaxLength(50)]
        public string LastName { get; set; }

        [Display(Name = ("Employee Code"))]
        [Required]
        [MaxLength(20)]
        public string Emp_Code { get; set; }

        [Display(Name = ("Date Of Birth"))]
        [Required]
        [DataType(DataType.Date)]
        public String DateOfBirth { get; set; }

        [Display(Name = ("Joining Date"))]
        [Required]
        [DataType(DataType.Date)]
        public String JoiningDate { get; set; }

        [Display(Name = ("Image"))]
        public string Image { get; set; }

        [Display(Name = ("Gender"))]
        [Required]
        public string Gender { get; set; }

        [Display(Name = ("Email"))]
        [Required]
        [DataType(DataType.EmailAddress)]
        public string EmailID { get; set; }

        [Display(Name = ("Mobile Number"))]
        [Required]
        [MaxLength(10)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string MobileNo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpAddressDet> EmpAddressDets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }

        public System.Web.HttpPostedFile ImageFile { get; set; }


    }
}
