//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpOrgWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enrollment
    {
        public int EnrollmentID { get; set; }

        [Display(Name = ("Salary"))]
        [Required]
        [RegularExpression(@"\d+(\.\d{1,2})?", ErrorMessage = "Invalid Salary.")]
        public Nullable<decimal> Salary { get; set; }

        [Display(Name = ("Department"))]
        [Required]
        public int Dept_ID { get; set; }

        [Display(Name = ("Employee"))]
        [Required]
        public int EmployeeID { get; set; }

        [Display(Name = ("State"))]
        [Required]
        public int StateID { get; set; }
    
        public virtual DepMst DepMst { get; set; }
        public virtual EmployeeMst EmployeeMst { get; set; }
        public virtual StateMst StateMst { get; set; }
    }
}
